input {
  tcp {
    mode => "server"
    host => "0.0.0.0"
    port => 5044
    codec => json_lines
  }
}

filter {

}

output {
  elasticsearch {
    # 直接用容器名：elasticsearch（Docker 网络内自动解析）
    hosts => "http://elasticsearch:9200"
    index => "tingshu-%{+YYYY.MM}"
    # 你 ES 已经关闭安全认证，所以这里删掉用户名密码
    # user => "elastic"
    # password => "111111"
  }
}